[project]
name = "ard"
version = "0.1.0"
description = "Autonomous Research Discovery tools"
authors = [{name = "Your Name"}]
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
